### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate… but memory is empty

### ISSUE THREAD

**Issue by pchampio** [idiap/pkwrap#11]
I was constantly getting a out of memory error even through I reduced my minibatch size.

I've replace 
https://github.com/idiap/pkwrap/blob/e055fbc32f72bf7d3925a2c146cbe82557c5ab26/pkwrap/chain.py#L687
and 
https://github.com/idiap/pkwrap/blob/e055fbc32f72bf7d3925a2c146cbe82557c5ab26/pkwrap/chain.py#L519
to
```py
minibatch_size=f"1:{chain_opts.minibatch_size.split(",")[-1]}", 
```

Is this correct ?
Thanks for this toolkit!

**Comment by mrsrikanth** [comment]
Right, that would work too. But before that I would test with a small minibatch size like 8 or 16. That should resolve your error, imo.

**Comment by pchampio** [comment]
thanks!
