### ISSUE TITLE
error: ‘cudaDataType_t’ does not name a type

### ISSUE THREAD

**Issue by MG623** [idiap/pkwrap#17]
Hello,during "make" step of pkwrap-master, an error occured. Below is the log, can you figure out what's the problem?

[log]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/hcg/kaldi-master/src/cudamatrix/cu-value.h:25:0,
                 from /home/hcg/kaldi-master/src/cudamatrix/cu-vector.h:33,
                 from /home/hcg/kaldi-master/src/cudamatrix/cu-matrix-lib.h:25,
                 from /home/hcg/kaldi-master/src/nnet3/nnet-common.h:28,
                 from /home/hcg/kaldi-master/src/nnet3/nnet-nnet.h:26,
                 from /home/hcg/kaldi-master/src/nnet3/am-nnet-simple.h:25,
                 from src/common.h:16,
                 from src/pkwrap-main.h:6,
                 from src/pkwrap-main.cc:4:
/home/hcg/kaldi-master/src/cudamatrix/cu-device.h:112:3: error: ‘cudaDataType_t’ does not name a type
   cudaDataType_t GetCublasComputeType() const { return cublas_compute_type_; }
   ^
/home/hcg/kaldi-master/src/cudamatrix/cu-device.h:114:3: error: ‘cublasGemmAlgo_t’ does not name a type
   cublasGemmAlgo_t GetCublasGemmAlgo() const { return cublas_gemm_algo_; }
   ^
/home/hcg/kaldi-master/src/cudamatrix/cu-device.h:381:3: error: ‘cudaDataType_t’ does not name a type
   cudaDataType_t cublas_compute_type_;
   ^
/home/hcg/kaldi-master/src/cudamatrix/cu-device.h:383:3: error: ‘cublasGemmAlgo_t’ does not name a type
   cublasGemmAlgo_t cublas_gemm_algo_;
   ^
error: command 'gcc' failed with exit status 1
Makefile:4: recipe for target 'package' failed
make: *** [package] Error 1

The environment is as follows
ubuntu1~16.04.12
gcc version 5.4.0
torch 1.8.1+cu111

**Comment by mrsrikanth** [comment]
Hello, 

Could you please tell me which version of Kaldi you are using? It will help me reproduce the error.

**Comment by MG623** [comment]
Thank you very much for your reminder. I tried to change the version of Kaldi (from the latest version "kaldi-master" to version "kaldi-trunk" in January 2020). Now it has been compiled successfully.Thanks again
