### ISSUE TITLE
EGS Librispeech (100h)

### ISSUE THREAD

**Issue by pchampio** [idiap/pkwrap#3]
In your technical report, there is a experiment using Librispeech (100h).
Are you planing to share this recipe?

I'm very interested in this particular experiment!

**Comment by mrsrikanth** [comment]
Yes, we will share all recipes from the report.As the interface has changed considerably, I'm merging the recipes and testing them once again before making it public. Librispeech recipe should be available in a few days time.

**Comment by pchampio** [comment]
Awesome, thanks!

**Comment by pchampio** [comment]
You have recently added a Librispeech recipe (on the 960h split).
Any update on the 100h split? 
Many thanks.

**Comment by mrsrikanth** [comment]
Hello,

I haven't pushed it yet because I have been re-organizing the scripts. Meanwhile, I will just push the current stable version this week.

Thank you,
Srikanth

**Comment by mrsrikanth** [comment]
Hello,

The 100h recipe is now available in ``egs/librispeech/v1/``.  The README is updated accordingly. Please let me know if you have issues/other questions.

Thanks,
Srikanth
